name: app_dimen
description: Collection of color with advanced controlling system.
version: 1.0.7
repository: https://github.com/Mohiuddin655-PUB/flutter_dimen.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_config: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true